import { useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { Icon } from '../../components/Icon';
import { Badge, Button, Card, EmptyState, Modal } from '../../components/Ui';
import { apiRequest } from '../../lib/api';
import type { Crop } from '../../lib/types';

export function CropsTab({ crops, reload }: { crops: Crop[]; reload(): Promise<void> }) {
  const [search, setSearch] = useState(''); const [editing, setEditing] = useState<Crop | null>(null); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [variety, setVariety] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const filtered = useMemo(() => crops.filter(crop => `${crop.name} ${crop.variety ?? ''}`.toLowerCase().includes(search.toLowerCase())), [crops, search]);
  function showCreate() { setEditing(null); setName(''); setVariety(''); setError(null); setOpen(true); }
  function showEdit(crop: Crop) { setEditing(crop); setName(crop.name); setVariety(crop.variety ?? ''); setError(null); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!name.trim()) { setError('Informe o nome da cultura.'); return; } setSaving(true); setError(null); try { const payload = { name: name.trim(), variety: variety.trim() || null }; await apiRequest(editing ? `/api/v1/crops/${editing.id}` : '/api/v1/crops/', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setOpen(false); await reload(); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível salvar a cultura.'); } finally { setSaving(false); } }
  async function deactivate(crop: Crop) { if (!window.confirm(`Desativar a cultura “${crop.name}”?`)) return; try { await apiRequest(`/api/v1/crops/${crop.id}`, { method: 'DELETE' }); await reload(); } catch (err) { window.alert(err instanceof Error ? err.message : 'Não foi possível desativar.'); } }
  return <Card className="resource-card"><div className="resource-toolbar"><div className="search-box"><Icon name="search" size={17} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar cultura ou variedade" aria-label="Buscar culturas" /></div><Button onClick={showCreate}><Icon name="plus" size={17} /> Nova cultura</Button></div>{filtered.length ? <div className="table-wrap"><table><thead><tr><th>Cultura</th><th>Variedade</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{filtered.map(crop => <tr key={crop.id}><td><strong>{crop.name}</strong><span className="table-sub">ID {crop.id.slice(0, 8)}</span></td><td>{crop.variety || '—'}</td><td><Badge tone={crop.isActive ? 'success' : 'neutral'}>{crop.isActive ? 'Ativa' : 'Inativa'}</Badge></td><td><div className="row-actions"><button className="icon-button" onClick={() => showEdit(crop)} aria-label={`Editar ${crop.name}`}><Icon name="edit" size={17} /></button><button className="icon-button icon-button--danger" onClick={() => void deactivate(crop)} aria-label={`Desativar ${crop.name}`}><Icon name="trash" size={17} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="Nenhuma cultura encontrada" description={search ? 'Ajuste a busca ou cadastre uma nova cultura.' : 'Cadastre a primeira cultura para usá-la nas safras.'} action={<Button onClick={showCreate}><Icon name="plus" size={16} /> Cadastrar cultura</Button>} />}<Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Editar cultura' : 'Nova cultura'}><form className="form-stack" onSubmit={submit}><label>Nome<input autoFocus required value={name} onChange={event => setName(event.target.value)} placeholder="Soja" /></label><label>Variedade<input value={variety} onChange={event => setVariety(event.target.value)} placeholder="Ex.: BMX Lança IPRO" /></label>{error && <div className="form-error" role="alert">{error}</div>}<div className="modal__actions"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving ? 'Salvando…' : 'Salvar cultura'}</Button></div></form></Modal></Card>;
}
