using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AgroControl.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AgroControlDbContext))]
[Migration("20260909010000_OfflineSyncChangeLog")]
public sealed class OfflineSyncChangeLog : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS offline_sync_changes (
                sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id uuid NOT NULL,
                farm_id uuid NULL,
                entity_kind varchar(32) NOT NULL,
                entity_id uuid NOT NULL,
                change_type varchar(16) NOT NULL,
                occurred_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX IF NOT EXISTS ix_offline_sync_changes_org_farm_sequence
                ON offline_sync_changes (organization_id, farm_id, sequence);
            CREATE INDEX IF NOT EXISTS ix_offline_sync_changes_org_kind_sequence
                ON offline_sync_changes (organization_id, entity_kind, sequence);
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_farm_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", OLD."Id", 'farm', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NEW."Id", 'farm', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_farms_offline_sync ON farms;
            CREATE TRIGGER trg_farms_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON farms
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_farm_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_field_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", OLD."FarmId", 'field', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                IF TG_OP = 'UPDATE' AND OLD."FarmId" IS DISTINCT FROM NEW."FarmId" THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", OLD."FarmId", 'field', OLD."Id", 'delete');

                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    SELECT
                        OLD."OrganizationId", OLD."FarmId", 'season', season."Id", 'delete'
                    FROM seasons AS season
                    WHERE season."OrganizationId" = OLD."OrganizationId"
                      AND season."FieldId" = OLD."Id";

                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (NEW."OrganizationId", NEW."FarmId", 'field', NEW."Id", 'upsert');

                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    SELECT
                        NEW."OrganizationId", NEW."FarmId", 'season', season."Id", 'upsert'
                    FROM seasons AS season
                    WHERE season."OrganizationId" = NEW."OrganizationId"
                      AND season."FieldId" = NEW."Id";

                    RETURN NEW;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NEW."FarmId", 'field', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_fields_offline_sync ON fields;
            CREATE TRIGGER trg_fields_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON fields
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_field_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_season_sync_change()
            RETURNS trigger AS $$
            DECLARE
                old_farm_id uuid;
                new_farm_id uuid;
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    SELECT "FarmId"
                      INTO old_farm_id
                      FROM fields
                     WHERE "OrganizationId" = OLD."OrganizationId"
                       AND "Id" = OLD."FieldId";

                    IF old_farm_id IS NULL THEN
                        RAISE EXCEPTION 'Cannot resolve farm for deleted season %', OLD."Id";
                    END IF;

                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", old_farm_id, 'season', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                SELECT "FarmId"
                  INTO new_farm_id
                  FROM fields
                 WHERE "OrganizationId" = NEW."OrganizationId"
                   AND "Id" = NEW."FieldId";

                IF new_farm_id IS NULL THEN
                    RAISE EXCEPTION 'Cannot resolve farm for season %', NEW."Id";
                END IF;

                IF TG_OP = 'UPDATE' THEN
                    SELECT "FarmId"
                      INTO old_farm_id
                      FROM fields
                     WHERE "OrganizationId" = OLD."OrganizationId"
                       AND "Id" = OLD."FieldId";

                    IF old_farm_id IS NULL THEN
                        RAISE EXCEPTION 'Cannot resolve previous farm for season %', OLD."Id";
                    END IF;

                    IF old_farm_id IS DISTINCT FROM new_farm_id THEN
                        INSERT INTO offline_sync_changes
                            (organization_id, farm_id, entity_kind, entity_id, change_type)
                        VALUES
                            (OLD."OrganizationId", old_farm_id, 'season', OLD."Id", 'delete');
                    END IF;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", new_farm_id, 'season', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_seasons_offline_sync ON seasons;
            CREATE TRIGGER trg_seasons_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON seasons
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_season_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_crop_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", NULL, 'crop', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NULL, 'crop', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_crops_offline_sync ON crops;
            CREATE TRIGGER trg_crops_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON crops
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_crop_sync_change();
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TRIGGER IF EXISTS trg_seasons_offline_sync ON seasons;
            DROP TRIGGER IF EXISTS trg_fields_offline_sync ON fields;
            DROP TRIGGER IF EXISTS trg_farms_offline_sync ON farms;
            DROP TRIGGER IF EXISTS trg_crops_offline_sync ON crops;

            DROP FUNCTION IF EXISTS agrocontrol_log_season_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_field_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_farm_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_crop_sync_change();

            DROP TABLE IF EXISTS offline_sync_changes;
            """);
    }
}
