using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AgroControl.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AgroControlDbContext))]
[Migration("20260909010000_OfflineSyncChangeLog")]
public sealed class OfflineSyncChangeLog : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS offline_sync_changes (
                sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                organization_id uuid NOT NULL,
                farm_id uuid NULL,
                entity_kind varchar(32) NOT NULL,
                entity_id uuid NOT NULL,
                change_type varchar(16) NOT NULL,
                occurred_at_utc timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX IF NOT EXISTS ix_offline_sync_changes_org_farm_sequence
                ON offline_sync_changes (organization_id, farm_id, sequence);
            CREATE INDEX IF NOT EXISTS ix_offline_sync_changes_org_kind_sequence
                ON offline_sync_changes (organization_id, entity_kind, sequence);
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_farm_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", OLD."Id", 'farm', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NEW."Id", 'farm', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_farms_offline_sync ON farms;
            CREATE TRIGGER trg_farms_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON farms
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_farm_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_field_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", OLD."FarmId", 'field', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NEW."FarmId", 'field', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_fields_offline_sync ON fields;
            CREATE TRIGGER trg_fields_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON fields
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_field_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_season_sync_change()
            RETURNS trigger AS $$
            DECLARE
                resolved_farm_id uuid;
                resolved_org_id uuid;
                resolved_field_id uuid;
                resolved_entity_id uuid;
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    resolved_org_id := OLD."OrganizationId";
                    resolved_field_id := OLD."FieldId";
                    resolved_entity_id := OLD."Id";
                ELSE
                    resolved_org_id := NEW."OrganizationId";
                    resolved_field_id := NEW."FieldId";
                    resolved_entity_id := NEW."Id";
                END IF;

                SELECT "FarmId"
                  INTO resolved_farm_id
                  FROM fields
                 WHERE "OrganizationId" = resolved_org_id
                   AND "Id" = resolved_field_id;

                IF resolved_farm_id IS NULL THEN
                    RAISE EXCEPTION 'Cannot resolve farm for season %', resolved_entity_id;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (
                        resolved_org_id,
                        resolved_farm_id,
                        'season',
                        resolved_entity_id,
                        CASE WHEN TG_OP = 'DELETE' THEN 'delete' ELSE 'upsert' END
                    );

                IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_seasons_offline_sync ON seasons;
            CREATE TRIGGER trg_seasons_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON seasons
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_season_sync_change();
            """);

        migrationBuilder.Sql(
            """
            CREATE OR REPLACE FUNCTION agrocontrol_log_crop_sync_change()
            RETURNS trigger AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    INSERT INTO offline_sync_changes
                        (organization_id, farm_id, entity_kind, entity_id, change_type)
                    VALUES
                        (OLD."OrganizationId", NULL, 'crop', OLD."Id", 'delete');
                    RETURN OLD;
                END IF;

                INSERT INTO offline_sync_changes
                    (organization_id, farm_id, entity_kind, entity_id, change_type)
                VALUES
                    (NEW."OrganizationId", NULL, 'crop', NEW."Id", 'upsert');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS trg_crops_offline_sync ON crops;
            CREATE TRIGGER trg_crops_offline_sync
            AFTER INSERT OR UPDATE OR DELETE ON crops
            FOR EACH ROW EXECUTE FUNCTION agrocontrol_log_crop_sync_change();
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            DROP TRIGGER IF EXISTS trg_seasons_offline_sync ON seasons;
            DROP TRIGGER IF EXISTS trg_fields_offline_sync ON fields;
            DROP TRIGGER IF EXISTS trg_farms_offline_sync ON farms;
            DROP TRIGGER IF EXISTS trg_crops_offline_sync ON crops;

            DROP FUNCTION IF EXISTS agrocontrol_log_season_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_field_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_farm_sync_change();
            DROP FUNCTION IF EXISTS agrocontrol_log_crop_sync_change();

            DROP TABLE IF EXISTS offline_sync_changes;
            """);
    }
}
