apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agrocontrol
resources:
  - namespace.yaml
  - configmap.yaml
  - api.yaml
  - intelligence.yaml
  - telemetry.yaml
  - web.yaml
  - pdb.yaml
